### ISSUE TITLE
How to programmatically start the Slideshow

### ISSUE THREAD

**Issue by xseignard** [vramana/react-flex-slick#2]
Hello,

Nice work on this slideshow, but i don't get how to programmatically start the slide show?

And how to programmatically set the slide to show?

Could you provide an example?

Regards,

Xavier

**Comment by vramana** [comment]
@xseignard Keep the currentSlide as state in the parent container and pass it down to Slider as a prop. Is this clear? or do I need to write an example?

**Comment by xseignard** [comment]
Yes it's ok!

I'll bake you an example so pple can find such info.

Regards
