### ISSUE TITLE
Does this work with server side rendering? no 'window' or 'document' dependencies?

### ISSUE THREAD

**Issue by Ajar-Ajar** [vramana/react-flex-slick#6]
I've been trying out too many carousel react components that assume they are running on the client and have 'window' and 'document' dependencies all over the place. This breaks the code trying to integrate it on an isomorphic app...

**Comment by vramana** [comment]
@Ajar-Ajar I haven't tried server-side rendering. I use setTimeout, clearTimeout, setInterval and clearInterval. Are they considered dependencies on window ?? I also use refs for touch event handling.
